### ISSUE TITLE
Error when using -g refGene.txt option

### ISSUE THREAD

**Issue by MeiShu00** [mcfrith/tandem-genotypes#10]
Hi, 

When i ran the following command `tandem-genotypes -g refGene.txt microstat.txt input.maf > output.txt`, i encountered the following error:

![image](https://user-images.githubusercontent.com/69883139/116029174-44ceca80-a68b-11eb-8c6b-40fb6fa11a25.png)

Hence, i would like to clarify the following questions:

1. I understand that it is ok to omit -g refGene.txt and i was able to get an output.txt file via this method. However, i would like to check if omitting the refgene.txt file would affect the output text file. 

2. As my reads are aligned using hg38 , i would also like to check if downloading the refGene table from UCSC table browser (https://genome-euro.ucsc.edu/cgi-bin/hgTables?hgsid=262439517_q2No2a0kysSpzsTA6blcVDh4e3nM&clade=mammal&org=Human&db=hg38&hgta_group=allTables&hgta_track=hg38&hgta_table=refGene&hgta_regionType=range&position=chr4%3A3%2C379%2C000-3%2C379%2C046&hgta_outputType=primaryTable&hgta_outFileName=SNP_loc_chr4%3A3379000-3379046.txt) is the same as the refGene.txt file that was mentioned in the README.md. I also got my microsat.txt file from the same source. 

Thank you :D

**Comment by mcfrith** [comment]
Thanks for reporting this problem, which helps to improve tandem-genotypes! It should be fixed in the newest version 1.8.2 (but I'm not sure when it will get into bioconda).

(The problem was that it didn't like the 1st line starting with "#" in your refGene.txt.)

If you omit -g refGene.txt, I think it only changes the gene annotations, and the order of the output lines (which are ordered by "importance").

If you download the table from there, I think it's the same (apart from the 1st line starting with "#"!)
