### ISSUE TITLE
Compatibility with faster aligner

### ISSUE THREAD

**Issue by MaestSi** [mcfrith/tandem-genotypes#4]
Dear tandem-genotypes developers,
I would like to know if the tool works only with Last alignment files or if you know of any other aligners that can produce a maf file more quickly.
I am asking this since, in my experience, Last is much slower than aligners as minimap2 that, however, seem to work only with paf and sam output formats.
Thanks in advance,
Simone

**Comment by satomimitsuhashi** [comment]
Dear Simone
I hope this helps...
I routinely use LAST for long read human genome data (~100Gb). It finishes alignment process within a day when I use -P16.
I found LAST is slightly slower than minimap2 but much faster than ngmlr, if I use masked reference. The method is described here (option 2).
https://github.com/mcfrith/last-rna/blob/master/last-long-reads.md
I have not found any major problems in using masked reference for tandem-genotypes analysis so far.
Satomi


2019/07/27 0:43、Simone Maestri <notifications@github.com<mailto:notifications@github.com>>のメール:


Dear tandem-genotypes developers,
I would like to know if the tool works only with Last alignment files or if you know of any other aligners that can produce a maf file more quickly.
I am asking this since, in my experience, Last is much slower than aligners as minimap2 that, however, seem to work only with paf and sam output formats.
Thanks in advance,
Simone

**Comment by MaestSi** [comment]
Thank you for the kind information.
Do you know if there is a way for converting maf format to bam format? I used maf-convert for converting maf to sam, but then I had no header, and so I could not compress it to bam.
What do you usually do if you want to inspect mapped reads in IGV, for example?
Thanks again

**Comment by satomimitsuhashi** [comment]
I think you just need to add -d option when making sam file, then cover to bam file using samtools like this.
maf-convert sam -d file.maf > file.sam
samtools view -bS -o file.bam file.sam
samtools sort file.bam sorted
samtools index file.bam
Hope this helps.





2019/07/27 23:59、Simone Maestri <notifications@github.com<mailto:notifications@github.com>>のメール:


Thank you for the kind information.
Do you know if there is a way for converting maf format to bam format? I used maf-convert for converting maf to sam, but then I had no header, and so I could not compress it to bam.
What do you usually do if you want to inspect mapped reads in IGV, for example?
Thanks again

**Comment by MaestSi** [comment]
Dear satomi,
thank you so much.
I had not understood that 'dictionary of sequence lengths' was something related with the sam header.
