### ISSUE TITLE
microsat.txt and refgene.txt setup

### ISSUE THREAD

**Issue by Tine-dk** [mcfrith/tandem-genotypes#7]
Hi,

In your microsat.txt file you have the following line:
`905	chr22	41994883	41994923	20xTG`
I miss some headers explaining what I see so that I can create a file myself.
The first column is the one I don't have any clue about.  Am I right about the rest of the columns?
1. ?
2. chromosome
3 start
4 end
5 reference repeat count * repeat pattern

Could you please explain the refGene.txt as well? I can see that it can be omitted, but does it have any consequences to omit it?
`905	NR_024355	chr22	+	41952186	41958942	41958942	41958942	2	41952186,41957671,	41952421,41958942,	0	LINC00634	unk	unk	-1,-1,`

**Comment by mcfrith** [comment]
Hi,

well it's not "our" microsat.txt file: it's from the UCSC genome database. You can get some explanation from their "table browser":
http://genome.ucsc.edu/cgi-bin/hgTables
Choose genome:Human, group:Repeats, track:Microsatellite.
I'm not sure what the 1st column is either: it's ignored by tandem-genotypes. I believe you're right about the other columns.

If I were creating a file myself, I would "supply repeats by the first 4 columns of the output format".

refGene.txt is also explained in the Table Browser. If you omit it, the rank-order of results will be different (because gene part info is missing).

I hope that clarifies things!
